name: app_testing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.5.0-36.0.dev <4.0.0'

dependencies: 
  get_cli: ^1.8.1
  google_fonts: ^6.2.1
  appwrite: ^12.0.3
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.5
  assets_audio_player: ^3.1.1
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

